### ISSUE TITLE
question about the extension of aflsmart

### ISSUE THREAD

**Issue by minifish120** [aflsmart/aflsmart#25]
i noticed your another work aflnet which dealed with protocol vulnerabilities with state-aware fuzzing, my question is : do you think the idea of aflsmart can be used to support field-aware message fuzzing in aflnet?if so, can you give me something guidelines about how to do it?

**Comment by thuanpv** [comment]
Hi @minifish120. Yes, integrating AFLSmart into AFLNet would improve the effectiveness of AFLNet. There are a few options that I was thinking about: 1) define Peach pit model for the whole message sequence, and 2) define Peach pit model for each type of request message. If you implement the first approach, you can use AFLSmart cracker to do what extract_requests_* functions currently do in AFLNet. However, AFLSmart cracker takes much longer time than extract_requests_* so it is not supposed to be called very frequently. If you implement the second approach, you would need to enhance AFLSmart to make it work with multiple input models at the same time if one input model could not be used to model all message types. The 3rd option is to simplify the cracker component of AFLSmart so that you can reduce significantly its overhead. The cracker is currently built on Peach and many components in Peach are not used. This option leverages the advantages of both options 1 and 2. You are welcome to share your thoughts :)
